export type Crag = {
    id: number,
    isFav: boolean,
    name: string,
    city: string,
    postalCode: string,
    lat: number,
    lon: number,
    altitude: number,
    rockType: string,
    minGrade: string,
    maxGrade: string,
    exposure: number,
    favorableSeasons?: string[],
    orientations?: string[],
    photoUrl: string,
    thumbnailUrl: string | null,
}